jobs/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from timeclock.views import MyRegistrationBackend
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'jobs.views.home', name='home'),
    # url(r'^jobs/', include('jobs.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^users', RedirectView.as_view(url='/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/', MyRegistrationBackend.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('jobboard.urls', namespace='jobboard')),
    url(r'^', include('timeclock.urls', namespace='timeclock')),
    
)

timeclock/urls.py
from django.conf.urls import patterns, url
from timeclock import views
from timeclock.views import EmployeeList, EmployeeDetail, EmployeeCreate, ClockCreate, EmployeeEdit, ClockEdit, ClockDisplay, ClockList, ClockDetail

urlpatterns = patterns('',
	url(r'^timeclock/$', EmployeeList.as_view(), name='index'),
	url(r'^timeclock/employee/all/(?P<pk>\d+)/$', ClockList.as_view(), name='all_clocks'),
	url(r'^timeclock/employee/(?P<pk>\d+)/$', EmployeeDetail.as_view(), name='employee'),
	url(r'^timeclock/employee/add/$', EmployeeCreate.as_view(), name='add_employee'),
	url(r'^timeclock/employee/edit/(?P<pk>\d+)/$', EmployeeEdit.as_view(), name='edit_employee'),
	url(r'^timeclock/employee/(?P<pk>\d+)/clock/add/$', ClockCreate.as_view(), name='add_clock'),
	url(r'^timeclock/employee/(?P<employee_id>\d+)/clock/edit/(?P<pk>\d+)/$', ClockEdit.as_view(), name='edit_clock'),
	url(r'^timeclock/clock/(?P<pk>\d+)/$', ClockDetail.as_view(), name='clock'),
	url(r'^timeclock/default/(?P<employee_id>\d+)/(?P<ran>\d+)/$', views.default_range, name='default_range'),
	url(r'^timeclock/default/all/(?P<ran>\d+)/$', views.default_range_all, name='default_range_all'),
)

timeclock/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

class Employee(models.Model):
	user = models.ForeignKey(User, unique=True)
	name = models.CharField(max_length=50)
	period_start = models.DateField(help_text= 'e.g. 10/09/2013')
	period_end = models.DateField(help_text= 'e.g. 10/09/2013')
	total_time = models.CharField(max_length=50, null=True)

	def get_absolute_url(self):
	        return reverse('timeclock:index')

	def __unicode__(self):
		return self.name

class Clock(models.Model):
	CLOCK_TYPES= (
	('Clock In', 'Clock In'),
	('Clock Out', 'Clock Out'),
	)

	employee = models.ForeignKey(Employee)
	clock_type = models.CharField('punch type',max_length=15, choices=CLOCK_TYPES)
	time = models.DateTimeField()
	project = models.ForeignKey('Project')
	total_time = models.CharField(max_length= 50, blank=True, null=True, editable=False)
	note = models.CharField(max_length= 200, blank=True, null=True)

	def get_absolute_url(self):
	        return reverse('timeclock:employee', args=(self.employee.id,))

	def __unicode__(self):
		return self.clock_type

class Project(models.Model):
	name = models.CharField(max_length=50)

	def __unicode__(self):
		return self.name

timeclock/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.admin import widgets
from timeclock.models import Employee, Clock

class AddEmployee(ModelForm):
	class Meta:
		model = Employee
		fields = ['name']

class AddClock(ModelForm):
	class Meta:
		model = Clock
		fields = ['clock_type','project', 'note']

class EditClock(ModelForm):
	class Meta:
		model = Clock
		fields = ['time', 'note']

class DateRangeForm(forms.Form):
	start_date = forms.DateField()
	end_date = forms.DateField()

timeclock/views.py
# Create your views here.
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic import ListView, DetailView, FormView, View
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages
import datetime
from datetime import time, date, timedelta
from django.utils import timezone
from registration.backends.simple.views import RegistrationView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from timeclock.models import Employee, Clock
from timeclock.forms import AddEmployee, AddClock, EditClock, DateRangeForm

class EmployeeList(ListView):
	context_object_name = 'employees'

	def get_queryset(self):
		user = self.request.user

		if int(user.id) == 1: #if the user is the admin show all employees
			return Employee.objects.all()

		else: #only show employees tied to the current user
			return Employee.objects.all().filter(user = user)
		
	def get_context_data(self, **kwargs):
		admin = False
		if self.request.user.id == 1:
			admin = True

		context = super(EmployeeList, self).get_context_data(**kwargs)
		context['admin'] = admin
		return context

	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(EmployeeList, self).dispatch(*args, **kwargs)

class ClockDetail(DetailView):
	context_object_name = 'clock'
	template_name = 'timeclock/clock_detail.html'	

	def get_object(self):
		user = self.request.user
		clock = get_object_or_404(Clock, pk = self.kwargs['pk'])
		if user.id == clock.employee.user.id or self.request.user.id == 1:
			return clock
		else:
			return get_object_or_404(Clock, pk = 10000000000000000)#this will 404 which is what I want, I'm sure there is a better way to do this, but i dont know how

	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(ClockDetail, self).dispatch(*args, **kwargs)
	
class ClockDisplay(ListView):
	context_object_name = 'clocks'
	template_name = 'timeclock/clock_list.html'
	def get_queryset(self):
		user = self.request.user
		employees = Employee.objects.all()
		start = employees[0].period_start#they will all be the same so why not use the first one?
		end = employees[0].period_end
		clocks = Clock.objects.all()
		if int(user.id) == 1: #if the user is the admin show all employees
			return clocks.filter(time__range=(start,end)).order_by('-time')

		else: #only show employees tied to the current user even though they shouldn't ever be here
			employee = Employee.objects.get(user = user)
			return Clock.objects.all().filter(employee = employee)

	def get_context_data(self, **kwargs):
		employees = Employee.objects.all()
		employee = employees[0]
		context = super(ClockDisplay, self).get_context_data(**kwargs)
		context['emp'] = employee
		context['form'] = DateRangeForm()
		return context

	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(ClockDisplay, self).dispatch(*args, **kwargs)

class ClockDateRange(SingleObjectMixin,FormView):
	template_name = 'timeclock/clock_list.html'
	form_class = DateRangeForm
	
	def get_queryset(self):
		return Employee.objects.all()

	def post(self, request, *args, **kwargs):
		self.object = self.get_object()
		return super(ClockDateRange, self).post(request, *args, **kwargs)

	def get_success_url(self):
		return reverse('timeclock:all_clocks', args=(1,))#I would choose to do this differently in the future

	def form_valid(self, form):
		employees = Employee.objects.all()
		for employee in employees:
			self.object.period_start = form.cleaned_data.get('start_date')
			self.object.period_end = form.cleaned_data.get('end_date')	
			self.object.save()
		return super(ClockDateRange, self).form_valid(form)

class ClockList(View):
	def get(self, request, *args, **kwargs):
		view = ClockDisplay.as_view()
		return view(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		view = ClockDateRange.as_view()
		return view(request, *args, **kwargs)


class EmployeeDisplay(DetailView):
	context_object_name = 'employee'
	template_name = 'timeclock/employee_detail.html'

	def get_queryset(self):

		if self.request.user.id == self.kwargs['pk'] or self.request.user.id == 1: #if it is current user or admin
			return Employee.objects.filter(pk = self.kwargs['pk'])
		else:
			return Employee.objects.all().filter(user = self.request.user )#this will 404 which is perfectly fine

	def get_context_data(self, **kwargs):
		start = Employee.objects.get(pk = self.kwargs['pk']).period_start
		end = Employee.objects.get(pk = self.kwargs['pk']).period_end

		context = super(EmployeeDisplay, self).get_context_data(**kwargs)
		clocks = Clock.objects.all().filter(employee = Employee.objects.filter(pk = self.kwargs['pk'])).order_by('-time')
		clocks = clocks.filter(time__range=(start,end))
		context['clocks'] = clocks
		context['form'] = DateRangeForm()
		return context
	
	@method_decorator(login_required)
    	def dispatch(self, *args, **kwargs):
        	return super(EmployeeDisplay, self).dispatch(*args, **kwargs)


class DateRange(SingleObjectMixin,FormView):
	template_name = 'timeclock/employee_detail.html'
	form_class = DateRangeForm
	
	def get_queryset(self):
		return Employee.objects.filter(pk = self.kwargs['pk'])

	def post(self, request, *args, **kwargs):
		self.object = self.get_object()
		return super(DateRange, self).post(request, *args, **kwargs)

	def get_success_url(self):
		return reverse('timeclock:employee', args=(self.object.id,))

	def form_valid(self, form):
		employee = Employee.objects.filter(pk = self.kwargs['pk'])
		self.object.period_start = form.cleaned_data.get('start_date')
		self.object.period_end = form.cleaned_data.get('end_date')	
		self.object.save()
		return super(DateRange, self).form_valid(form)

	
class EmployeeDetail(View):
	def get(self, request, *args, **kwargs):
		view = EmployeeDisplay.as_view()
		return view(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		view = DateRange.as_view()
		return view(request, *args, **kwargs)


class EmployeeCreate(CreateView):
	model = Employee
	template_name = 'timeclock/employee_create.html'
	form_class = AddEmployee
	
	def get_form(self, form_class):
		one_day_ago = timezone.now().date() - timedelta(days=1)
		tomorrow =  timezone.now().date() + timedelta(days=1)
		form = super(EmployeeCreate, self).get_form(form_class)
		form.instance.user = self.request.user
		form.instance.period_start = one_day_ago
		form.instance.period_end = tomorrow
		return form

class EmployeeEdit(UpdateView):
	model = Employee
	template_name = 'timeclock/employee_update.html'
	form_class = AddEmployee

	def get_form(self, form_class):
		form = super(EmployeeEdit, self).get_form(form_class)
		form.instance.user = self.request.user
		return form

class ClockCreate(CreateView):
	model = Clock
	template_name = 'timeclock/clock_create.html'
	form_class = AddClock

	def get_form(self, form_class):
		employee = get_object_or_404(Employee, pk = self.kwargs['pk'])
		form = super(ClockCreate, self).get_form(form_class)
		form.instance.employee = employee
		form.instance.time = timezone.now()
		return form

	def form_valid(self, form):
		employee = get_object_or_404(Employee, pk = self.kwargs['pk'])
		clocks = Clock.objects.all().filter(employee = employee).order_by('-pk')
		self.object = form.save(commit=False)
		if clocks: #making sure that users follow the rules
#			if self.object.clock_type == 'Clock Out':#update the total time on a clock out
#				if clocks[0].clock_type == 'Clock In':
#					total = self.object.time - clocks[0].time
#					hours, remainder = divmod(total.seconds, 3600)
#					minutes, seconds = divmod(remainder, 60)
#					total_time_string = "%02d:%02d:%02d" % (hours, minutes, seconds)
#					self.object.total_time = total_time_string
#					self.object.save()
#			else:#want total_time to be empty
#				self.object.total_time = ''
#				self.object.save()

			if not clocks[0].clock_type == self.object.clock_type:
				if clocks[0].clock_type == 'Clock In':
					if clocks[0].project == self.object.project:
						self.object.save()
						messages.success(self.request, str(self.object.clock_type) + ' successful!')
						return super(ClockCreate, self).form_valid(form)
					else:
						messages.error(self.request,'You tried to clock out on ' + str(self.object.project) + ' , but you are currently clocked in on ' + str(clocks[0].project))
				else:
					self.object.save()
					messages.success(self.request, str(self.object.clock_type) + ' successful!')
					return super(ClockCreate, self).form_valid(form)
			else:
				messages.error(self.request,'You tried to ' + str(self.object.clock_type) + ', but you already were.')
		
		else:
			self.object.save()
			messages.success(self.request, str(self.object.clock_type) + ' successful!')
			return super(ClockCreate, self).form_valid(form)

		return HttpResponseRedirect(reverse('timeclock:employee', args=(employee.id,)))

	def get_initial(self):
		employee = get_object_or_404(Employee, pk = self.kwargs['pk'])
		clocks = Clock.objects.all().filter(employee = employee).order_by('-pk')
		initial = super(ClockCreate, self).get_initial()
		initial = initial.copy()

		if clocks:
			if clocks[0].clock_type == 'Clock In':
				ct = 'Clock Out'
				proj = clocks[0].project
			else:
				ct = 'Clock In'
				proj = None
			initial['clock_type'] = ct
			initial['project'] = proj
		return initial

class ClockEdit(UpdateView):
	model = Clock
	template_name = 'timeclock/clock_update.html'
	form_class = EditClock
	
	def get_form(self, form_class):
		employee = get_object_or_404(Employee, pk = self.kwargs['employee_id'])
		form = super(ClockEdit, self).get_form(form_class)
		form.instance.employee = employee
		return form

	def form_valid(self, form):

timeclock/templates/timeclock/clock_create.html
{% extends "timeclock_base.html" %}

{% block content %}
<div class="jumbotron">
	<h1>Clock in or out</h1>
	<form method="POST" action="." id="clock-add-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Punch Clock"></input>
        </form>
</div>

{% endblock %}

timeclock/templates/timeclock/clock_detail .html
{% extends "timeclock_base.html" %}

{% block content %}
<div class="jumbotron">
	<h1>Punch Detail</h1>
	<h4>Employee: {{ clock.employee.name }}</h4>
	<h4>Punch Type: {{ clock.clock_type }}</h4>	
	<h4>Time: {{ clock.time }}</h4>
	<h4>Project: {{ clock.project }}</h4>
	<h4>Note:</h4>
	<p>{{ clock.note }}</p>
</div>

{% endblock %}

timeclock/templates/timeclock/clock_detail.html
{% extends "timeclock_base.html" %}

{% block content %}
<div class="jumbotron">
	<h1>Punch Detail</h1>
	<h4>Employee: {{ clock.employee.name }}</h4>
	<h4>Punch Type: {{ clock.clock_type }}</h4>	
	<h4>Time: {{ clock.time }}</h4>
	<h4>Project: {{ clock.project }}</h4>
	<h4>Note:</h4>
	<h5>{{ clock.note }}</h5>
</div>

{% endblock %}

timeclock/templates/timeclock/clock_list.html
{% extends "timeclock_base.html" %}

{% block content %}
<div class="jumbotron">
{% if clocks %}
	<h1>All Employees Punches</h1>
	<h4>Filter the punches by date range</h4>
	<form method="POST" action="." id="date-range-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Search"></input>
        </form>
	<h4>Currently viewing punches in the date range: {{emp.period_start}} - {{emp.period_end}}</h4>
	<h4>See the last <a href="{% url 'timeclock:default_range_all' 1 %}">week</a>-<a href="{% url 'timeclock:default_range_all' 2 %}">2 weeks</a>-<a href="{% url 'timeclock:default_range_all' 4 %}">month</a></h4>
	<hr>
	<table class="job-table">
		<tr>
		<th>Name</th>
		<th>In/Out</th>
		<th>Time</th>
		<th>Project</th>
		<th></th>
		</tr>
		{% for clock in clocks %}
			<tr>
			<td><a href="{% url 'timeclock:employee' clock.employee.id %}">{{ clock.employee.name }}</a></td>
			<td>{{ clock.clock_type }}</td>
			<td>{{ clock.time }}</td>
			<td>{{ clock.project }}</td>
			<td><a href="{% url 'timeclock:clock' clock.id %}">Details</a></td>
			</tr>
		{% endfor %}

	</table>
{% endif %}
</div>

{% endblock %}

timeclock/templates/timeclock/clock_update.html
{% extends "timeclock_base.html" %}

{% block content %}
<div class="jumbotron">
	<h1>Edit punch</h1>
	<form method="POST" action="." id="clock-edit-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Edit Punch"></input>
        </form>
</div>

{% endblock %}

timeclock/templates/timeclock/employee_create.html
{% extends "timeclock_base.html" %}

{% block content %}
<div class="jumbotron">
	<h1>Create your profile</h1>
	<form method="POST" action="." id="employee-add-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Create Employee"></input>
        </form>
</div>

{% endblock %}

timeclock/templates/timeclock/employee_detail.html
{% extends "timeclock_base.html" %}

{% block content %}
<div class="jumbotron">
	<h1>Employee: {{employee.name}}</h1>
	<h4><a href="{% url 'timeclock:add_clock' employee.id %}">Punch Clock</a></h4>
	<h4>or</h4>
	<h4>Filter the punches by date range</h4>
	<form method="POST" action="." id="date-range-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Search"></input>
        </form>
	{% if clocks %}
		<h4>Currently viewing punches in the date range: {{employee.period_start}} - {{employee.period_end}}</h4>
		<h4>See the last <a href="{% url 'timeclock:default_range' employee.id 1 %}">week</a>-<a href="{% url 'timeclock:default_range' employee.id 2 %}">2 weeks</a>-<a href="{% url 'timeclock:default_range' employee.id 4 %}">month</a></h4>
		<hr>
		<table class="job-table">
		<tr>
		<th>In/Out</th>
		<th>Time</th>
		<th>Project</th>
		<th></th>
		<th></th>
		</tr>
		{% for clock in clocks %}
			<tr>
			<td>{{clock.clock_type}}</td>
			<td>{{clock.time}}</td>
			<td>{{clock.project}}</td>
			<td><a href="{% url 'timeclock:clock' clock.id %}">Details</a></td>
			<td><a href="{% url 'timeclock:edit_clock' employee.id clock.id %}">Edit</a></td>
			</tr>
		{% endfor %}
		</table>
	{% else %}
		<h3>No punches available in the date range: {{employee.period_start}} - {{employee.period_end}}</h3>
		<h4>See the last <a href="{% url 'timeclock:default_range' employee.id 1 %}">week</a>-<a href="{% url 'timeclock:default_range' employee.id 2 %}">2 weeks</a>-<a href="{% url 'timeclock:default_range' employee.id 4 %}">month</a></h4>
	{% endif %}
</div>

{% endblock %}

timeclock/templates/timeclock/employee_list.html
{% extends "timeclock_base.html" %}

{% block content %}
<div class="jumbotron">
{% if employees %}
	<h1>Employee Information</h1>
	{% if admin %}
		<h4><a href="{% url 'timeclock:all_clocks' 1 %}">View all employees</a></h4>
	{% endif %}
	<table class="job-table">
		<tr>
		<th>Name</th>
		<th>Time Period Start</th>
		<th>Time Period End</th>
		<th></th>
		<th></th>
		</tr>
		{% for employee in employees %}
			<tr>
			<td><a href="{% url 'timeclock:employee' employee.id %}">{{ employee.name }}</a></td>
			<td>{{ employee.period_start }}</td>
			<td>{{ employee.period_end }}</td>
			<td><a href="{% url 'timeclock:add_clock' employee.id %}">Punch Clock</a></td>
			<td><a href="{% url 'timeclock:edit_employee' employee.id %}">Update Info</a></td>
			</tr>
		{% endfor %}

	</table>
{% else %}
	<h1>Welcome to the time clock, please <a href="{% url 'timeclock:add_employee' %}">create an employee profile</a></h1>
{% endif %}
</div>

{% endblock %}

timeclock/templates/timeclock/employee_update.html
{% extends "timeclock_base.html" %}

{% block content %}
<div class="jumbotron">
	<h1>Update your profile</h1>
	<form method="POST" action="." id="employee-add-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Update Employee"></input>
        </form>
</div>

{% endblock %}