jobboard/urls.py
from django.conf.urls import patterns, include, url
from jobboard import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^job/(?P<job_id>\d+)/$', views.job_detail, name='job_detail'),
    url(r'^job_add/$', views.add_job, name='job_add'),
    url(r'^job/edit/(?P<job_id>\d+)/$', views.edit_job, name='job_edit'),
    url(r'^employer/(?P<employer_id>\d+)/$', views.employer_detail, name='employer_detail'),
    url(r'^employer_add/$', views.add_employer, name='employer_add'),
    url(r'^employer/edit/(?P<employer_id>\d+)/$', views.edit_employer, name='employer_edit'),
    url(r'^subscribe/$', views.add_subscriber, name='subscriber_add'),
    url(r'^unsubscribe/$', views.del_subscriber, name='subscriber_del'),
)

jobs/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from timeclock.views import MyRegistrationBackend
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'jobs.views.home', name='home'),
    # url(r'^jobs/', include('jobs.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^users', RedirectView.as_view(url='/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/', MyRegistrationBackend.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('jobboard.urls', namespace='jobboard')),
    url(r'^', include('timeclock.urls', namespace='timeclock')),
    
)

jobboard/models.py
from django.db import models
from django.contrib.auth.models import User

class Employer(models.Model):
	user = models.ForeignKey(User)
	name = models.CharField(max_length=200)
	description = models.TextField()
	website = models.URLField(help_text= 'e.g. http://www.abc.com')
	email = models.EmailField('preferred contact email address')
	contact = models.CharField('contact name', max_length=30)

	def __unicode__(self):
                return self.name

class Job(models.Model):
	JOB_TYPES= (
	('Part Time', 'Part Time'),
	('Full Time', 'Full Time'),
	('Internship', 'Internship'),
	)	

	employer = models.ForeignKey(Employer)
	title = models.CharField(max_length=50)
	description = models.TextField()
	job_type = models.CharField(max_length=50, choices=JOB_TYPES)
	wage = models.CharField(max_length=50, help_text= 'e.g. $7.25 per hour, or $40,000 per year')
	pub_date = models.DateTimeField(auto_now_add=True)
	expiry_date = models.DateField(help_text= 'e.g. 10/09/2013')
	active = models.BooleanField()

	def __unicode__(self):
                return self.title

class Subscriber(models.Model):
	name = models.CharField(max_length=50)
	email = models.EmailField(unique=True)

	def __unicode__(self):
                return self.email

jobboard/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.admin import widgets
from jobboard.models import Employer, Job, Subscriber

class AddEmployer(ModelForm):
	class Meta:
		model = Employer
		widgets = {
                        'description': forms.Textarea(attrs={'rows':3, 'cols':15}),
                }
		fields=['name','description','website','email','contact']

class AddJob(ModelForm):
	class Meta:
		model = Job
		widgets = {
                        'description': forms.Textarea(attrs={'rows':3, 'cols':15}),
                }
		exclude=('pub_date',)

class EditEmployer(ModelForm):
	class Meta:
		model = Employer
		widgets = {
                        'description': forms.Textarea(attrs={'rows':3, 'cols':15}),
                }
		fields=['name','description','website','email','contact']

class EditJob(ModelForm):
	class Meta:
		model = Job
		widgets = {
                        'description': forms.Textarea(attrs={'rows':3, 'cols':15}),
                }
		exclude=('pub_date',)

class AddSubscriber(ModelForm):
	class Meta:
		model = Subscriber
		fields=['name','email']

class DelSubscriber(forms.Form):
	email = forms.EmailField()

class Contact(forms.Form):
	name = forms.CharField(max_length=50)
	email = forms.EmailField()
	phone = forms.CharField(max_length=14)
	message = forms.CharField(widget=forms.Textarea(attrs={'rows':3, 'cols':15}))

jobboard/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.template import RequestContext, loader
import datetime
from django.utils import timezone

from jobboard.models import Employer, Job, Subscriber
from jobboard.forms import AddEmployer, AddJob, EditEmployer, EditJob, AddSubscriber, DelSubscriber, Contact

def index(request):
	unactivate() #do this first thing on the index page to make sure it is up to date
        user = request.user
        all_jobs = Job.objects.all().order_by('-pub_date')
        recent_jobs = all_jobs.filter(active=True)[:5]
        employers = Employer.objects.all()
        jobs = all_jobs.filter(active=True)
        context= {
        'user':user,
        'recent_jobs':recent_jobs,
        'employers':employers,
        'jobs':jobs,
        }
        return render(request, 'jobboard/index.html', context)

def job_detail(request, job_id):
	user = request.user
	employers = Employer.objects.all()
	all_jobs = Job.objects.all().order_by('-pub_date')
	recent_jobs = all_jobs.filter(active=True)[:5]
	job = get_object_or_404(Job, pk=job_id, active=True)#only show the page if the job is active
	form = Contact(request.POST or None)
	if form.is_valid():
		cd = form.cleaned_data
		name = cd.get('name')
		email = cd.get('email')
		phone = cd.get('phone')
		message = cd.get('message')
		contact = job.employer.contact
		title = job.title
		template = loader.get_template('jobboard/contact_email.txt')
		context = RequestContext(request, {'name':name, 'email':email, 'phone':phone, 'message':message, 'contact':contact, 'title':title, })
		body = template.render(context)
		send_mail('Message about posted job: on the CIT Job Board', body, 'no-reply@betterjobboard.com', [job.employer.email],fail_silently=False)
		messages.success(request, 'Your message has been sent to the employer.')
	elif form.errors:
		messages.error(request, 'Something went wrong, please try again.')
		
	context= {
	'user':user,
	'recent_jobs':recent_jobs,
	'employers':employers,
	'job':job,
	'form':form,
	}
	return render(request, 'jobboard/job_detail.html', context)

def employer_detail(request, employer_id):
	user = request.user
	employers = Employer.objects.all()
	all_jobs = Job.objects.all().order_by('-pub_date')
	recent_jobs = all_jobs.filter(active=True)[:5]
	employer = get_object_or_404(Employer, pk=employer_id)
	jobs = all_jobs.filter(employer__id=employer_id)#these are the jobs you will see if you are the user who made the employer
	cur_user = False
	if(user.id > 0):#just checking to make sure there is a user
		if int(user.id) == int(employer.user.id):
			cur_user = True

	if not cur_user:
		jobs = jobs.filter(active=True)#these are the jobs you will see if you aren't the user who made the employer

	context= {
	'user':user,
	'recent_jobs':recent_jobs,
	'employer':employer,
	'employers':employers,
	'jobs':jobs,
	'cur_user':cur_user,
	}
	return render(request, 'jobboard/employer_detail.html', context)

@login_required
def add_employer(request):
	user = request.user
	employers = Employer.objects.all()
	all_jobs = Job.objects.all().order_by('-pub_date')
	recent_jobs = all_jobs.filter(active=True)[:5]
	employer = Employer(user=user)
	form = AddEmployer(request.POST or None, instance=employer)
	
	if form.is_valid():
		form.save()
		messages.success(request, 'Successfully added an employer.')
	elif form.errors:
		messages.error(request, 'Something went wrong, please try again.')
	context= {
	'user':user,
	'recent_jobs':recent_jobs,
	'employers':employers,
	'form':form,
	}
	return render(request, 'jobboard/employer_add.html', context)

@login_required
def edit_employer(request, employer_id):
	user = request.user
	employers = Employer.objects.all()
	employer = get_object_or_404(Employer, pk=employer_id)
	all_jobs = Job.objects.all().order_by('-pub_date')
	recent_jobs = all_jobs.filter(active=True)[:5]
	cur_user = False
	if(user.id > 0):#just checking to make sure there is a user
		if int(user.id) == int(employer.user.id):
			cur_user = True
		else:
			messages.error(request, 'You are unable to edit this employer as you are not the owner.')
	form = EditEmployer(request.POST or None, instance = employer)
	if cur_user:
		if form.is_valid():
			form.save()
			messages.success(request, 'Successfully edited employer.')
		elif form.errors:
			messages.error(request, 'Something went wrong, please try again.')
			#return HttpResponseRedirect(reverse('jobboard:employer_detail', args=(employer.id,)))

	context= {
	'user':user,
	'recent_jobs':recent_jobs,
	'employers':employers,
	'employer':employer,
	'form':form,
	'cur_user':cur_user,
	}
	return render(request, 'jobboard/employer_edit.html', context)

@login_required
def add_job(request):
	user = request.user
	employers = Employer.objects.all()
	all_jobs = Job.objects.all().order_by('-pub_date')
	recent_jobs = all_jobs.filter(active=True)[:5]
	form = AddJob(request.POST or None)
	form.fields['employer'].queryset = Employer.objects.all().filter(user=user)

	if form.is_valid():
		form.save()
		
		new_job=Job.objects.order_by('-pk')[0] #this seems kinda hacky
		if new_job.active:
			notify_subscribers(request, new_job.id)
			messages.success(request, 'Successfully added a job. Emails have been sent to subscribers')
		else:
			messages.success(request, 'Successfully added a job, but it is not currently active')
	elif form.errors:
		messages.error(request, 'Something went wrong, please try again.')
	context= {
	'user':user,
	'recent_jobs':recent_jobs,
	'employers':employers,
	'form':form,
	}
	return render(request, 'jobboard/job_add.html', context)

@login_required
def edit_job(request, job_id):
	user = request.user
	employers = Employer.objects.all()
	all_jobs = Job.objects.all().order_by('-pub_date')
	recent_jobs = all_jobs.filter(active=True)[:5]
	job = get_object_or_404(Job, pk=job_id)
	cur_user = False
	if int(user.id) == int(job.employer.user.id):
		cur_user = True
	form = EditJob(request.POST or None, instance=job)
	if cur_user:
		if form.is_valid():
			form.save()
			messages.success(request, 'Successfully edited job.')
		elif form.errors:
			messages.error(request, 'Something went wrong, please try again.')
			#return HttpResponseRedirect(reverse('jobboard:job_detail', args=(job.id,)))

	else:
		messages.error(request, 'You did not create this job, therefore you cannot edit it.')
	context= {
	'user':user,
	'recent_jobs':recent_jobs,
	'employers':employers,
	'job':job,
	'form':form,
	'cur_user':cur_user,
	}
	return render(request, 'jobboard/job_edit.html', context)

def add_subscriber(request):
	user = request.user
	employers = Employer.objects.all()
	all_jobs = Job.objects.all().order_by('-pub_date')
	recent_jobs = all_jobs.filter(active=True)[:5]
	form = AddSubscriber(request.POST or None)
	if form.is_valid():
		form.save()
		messages.success(request, 'You have successfully subscribed to job post emails.')
	elif form.errors:
		messages.error(request, 'Something went wrong, please try again.')
	
	context= {
	'user':user,
	'recent_jobs':recent_jobs,
	'employers':employers,
	'form':form,
	}
	return render(request, 'jobboard/subscriber_add.html', context)

def del_subscriber(request):
	user = request.user
	employers = Employer.objects.all()
	all_jobs = Job.objects.all().order_by('-pub_date')
	recent_jobs = all_jobs.filter(active=True)[:5]
	form = DelSubscriber(request.POST or None)
	if form.is_valid():
		cd = form.cleaned_data
		try:
			sub = Subscriber.objects.get(email = cd.get('email'))
			sub.delete()
			messages.success(request, 'You have been unsubscribed from emails about job listings.')
		except Subscriber.DoesNotExist:
			messages.error(request, 'The email you have entered is not currently subscribed to job listings.')
		
	elif form.errors:
		messages.error(request, 'Something went wrong, please try again.')

	context= {
	'user':user,
	'recent_jobs':recent_jobs,
	'employers':employers,
	'form':form,
	}
	return render(request, 'jobboard/subscriber_del.html', context)

def notify_subscribers(request, job_id):
	#send the mass emails
	job = Job.objects.get(pk=job_id)
	subscribers = Subscriber.objects.all()
	for subscriber in subscribers:

		template = loader.get_template('jobboard/email.txt')
		context = RequestContext(request, {'name':subscriber.name, 'title':job.title, 'employer':job.employer.name, 'job_id':job.id,})
		body = template.render(context)
		send_mail('New Job Posting: on Job Board', body, 'no-reply@jobboard.com', [subscriber.email], fail_silently=True)
	return True

def unactivate():
	today = datetime.date.today()
	jobs = Job.objects.all()
	for job in jobs:
		if job.expiry_date < today:
			job.active = False
			job.save()

jobboard/templates/jobboard/employer_add.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}CIT Job Board-Add Employer{% endblock %}

{% block content %}

<div class="jumbotron">
	<h1>{{user}}, you are adding a new Employer</h1>
	<form method="POST" action="." id="employer-add-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Add Employer"></input>
        </form>
</div>

{% endblock %}

jobboard/templates/jobboard/employer_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}CIT Job Board-Detail{% endblock %}

{% block content %}

<div class="jumbotron">
	{% if cur_user %}
		<a href="{% url 'jobboard:employer_edit' employer.id %}" >Edit Employer Info</a>
	{% endif %}
	<h1>{{employer}}</h1>
	<h4>Website: <a href="{{employer.website}}">{{employer.website}}</a></h4>
	<h4>Contact: {{employer.contact}} at: {{employer.email}}</h4>
	<p class="info">{{employer.description}}</p>

	{% if jobs %}
	<h3>Available jobs</h3>
	<table class="job-table">
		<tr>
		<th>Job Title</th>
		<th>Description</th>
		<th>FT/PT</th>
		<th>Wage</th>
		<th>Expires</th>
		{% if cur_user %}
			<th>Active?</th>
			<th></th>
		{% endif %}
		</tr>
		{% for job in jobs %}
			<tr>
			<td><a href="{% url 'jobboard:job_detail' job.id %}">{{job.title}}</a></td>
			<td>{{job.description}}</td>	
			<td>{{job.job_type}}</td>
			<td>{{job.wage}}</td>
			<td>{{job.expiry_date}}</td>
			{% if cur_user %}
				<td>{{job.active}}</td>
				<td><a href="{% url 'jobboard:job_edit' job.id %}">Edit Job</a>
			{% endif %}
			</tr>
		{% endfor %}
	</table>
	{% endif %}
</div>

{% endblock %}

jobboard/templates/jobboard/employer_edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}CIT Job Board-Edit Employer{% endblock %}

{% block content %}

<div class="jumbotron">
	<h1>{{user}}, you are editing {{employer.name}}</h1>
	<form method="POST" action="." id="employer-edit-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Edit Employer"></input>
        </form>
</div>

{% endblock %}

jobboard/templates/jobboard/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}CIT Job Board-Index{% endblock %}

{% block content %}

<div class="jumbotron">
	<h1>Available Jobs</h1>
	{% if jobs %}
	<table class="job-table">
		<tr>
		<th>Employer</th>
		<th>Job Title</th>
		<th>Description</th>
		<th>FT/PT</th>
		<th>Wage</th>
		</tr>
		{% for job in jobs %}
			<tr>
			<td><a href="{% url 'jobboard:employer_detail' job.employer.id %}">{{job.employer}}</a></td>
			<td><a href="{% url 'jobboard:job_detail' job.id %}">{{job.title}}</a></td>
			<td>{{job.description}}</td>	
			<td>{{job.job_type}}</td>
			<td>{{job.wage}}</td>
			</tr>
		{% endfor %}
	</table>
	{% endif %}
	<a href="{% url 'jobboard:subscriber_add' %}"><p class="subscribe">Subscribe or unsubscribe from job updates</p></a>
</div>

{% endblock %}

jobboard/templates/jobboard/job_add.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}CIT Job Board-Add Job{% endblock %}

{% block content %}

<div class="jumbotron">
	<h1>{{user}}, you are adding a new Job</h1>
	<form method="POST" action="." id="job-add-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Add Job"></input>
        </form>
	<p>please allow up to a minute for this job to post</p>
</div>

{% endblock %}

jobboard/templates/jobboard/job_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}CIT Job Board-Detail{% endblock %}

{% block content %}

<div class="jumbotron">
	<h1>{{job.title}} at <a href="{% url 'jobboard:employer_detail' job.employer.id %}">{{job.employer}}</a></h1>
	<h4>Listed on: {{job.pub_date}} Until: {{job.expiry_date}}</h4>
	<h4>Wage: {{job.wage}} Type: {{job.job_type}}</h4>
	<p class="info">{{job.description}}</p>
	<hr>
	<h3>Contact {{job.employer}} about this job</h3>
	<form method="POST" action="." id="contact-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Contact Employer"></input>
        </form>
	<hr>
	<h3>About {{job.employer}}</h3>
	<h4>Website: <a href="{{job.employer.website}}">{{job.employer.website}}</a></h4>
	<h4>Contact: {{job.employer.contact}} at: {{job.employer.email}}</h4>
	<p class="info">{{job.employer.description}}</p>
</div>

{% endblock %}

jobboard/templates/jobboard/job_edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}CIT Job Board-Edit Job{% endblock %}

{% block content %}

<div class="jumbotron">
	<h1>{{user}}, you are editing {{job.title}} for {{job.employer.name}}</h1>
	<form method="POST" action="." id="job-edit-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Edit Job"></input>
        </form>
</div>

{% endblock %}

jobboard/templates/jobboard/subscriber_add.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}CIT Job Board-Subscribe{% endblock %}

{% block content %}

<div class="jumbotron">
	<a href="{% url 'jobboard:subscriber_del' %}">Unsubscribe from updates</a>
	<h1>Subscribe to recieve updates on job listings</h1>
	<form method="POST" action="." id="subscriber-add-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Subscribe"></input>
        </form>
</div>

{% endblock %}

jobboard/templates/jobboard/subscriber_del.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}CIT Job Board-Subscribe{% endblock %}

{% block content %}

<div class="jumbotron">
	<h1>Unsubscribe from updates on job listings</h1>
	<form method="POST" action="." id="subscriber-del-form">
                <table class="form">
                {% csrf_token %}
                {{form}}
                </table>
                <input class="btn" type="submit" value="Unsubscribe"></input>
        </form>
</div>

{% endblock %}