jobboard/urls.py
from django.conf.urls import patterns, include, url
from jobboard import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^job/(?P<job_id>\d+)/$', views.job_detail, name='job_detail'),
    url(r'^job_add/$', views.add_job, name='job_add'),
    url(r'^job/edit/(?P<job_id>\d+)/$', views.edit_job, name='job_edit'),
    url(r'^employer/(?P<employer_id>\d+)/$', views.employer_detail, name='employer_detail'),
    url(r'^employer_add/$', views.add_employer, name='employer_add'),
    url(r'^employer/edit/(?P<employer_id>\d+)/$', views.edit_employer, name='employer_edit'),
    url(r'^subscribe/$', views.add_subscriber, name='subscriber_add'),
    url(r'^unsubscribe/$', views.del_subscriber, name='subscriber_del'),
)

jobs/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import RedirectView
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from timeclock.views import MyRegistrationBackend
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'jobs.views.home', name='home'),
    # url(r'^jobs/', include('jobs.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^users', RedirectView.as_view(url='/')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/register/', MyRegistrationBackend.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('jobboard.urls', namespace='jobboard')),
    url(r'^', include('timeclock.urls', namespace='timeclock')),
    
)

jobs/templates/base.html
{% load staticfiles %}
<!DOCTYPE html> 
<html lang="en"> 
<head> 
	<meta charset="utf-8"> 
	{% block title %}<title>CIT-Job Board</title>{% endblock %}
	<link href='http://fonts.googleapis.com/css?family=Titillium+Web:600' rel='stylesheet' type='text/css'>
	<link rel ="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<link rel ="stylesheet" href="{% static 'style.css' %}">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script>
	<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
	{% block scripts %}{% endblock %}
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
		<ul class="nav">
		  <li class="active">
		    <a class="brand" href="{% url 'jobboard:index' %}">CIT-Job Board</a>
		  </li>
		  <li class="dropdown">
                    <a href="#"
                          class="dropdown-toggle"
                          data-toggle="dropdown">
                          Recent Jobs
                          <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                     {% for job in recent_jobs %}
                     <li><a href="{% url 'jobboard:job_detail' job.id %}">{{job.title}}</a></li>
                     {% endfor %}
                    </ul>
                  </li>
		  <li class="dropdown">
                    <a href="#"
                          class="dropdown-toggle"
                          data-toggle="dropdown">
                          Employers
                          <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                     {% for employer in employers %}
                     <li><a href="{% url 'jobboard:employer_detail' employer.id %}">{{employer.name}}</a></li>
                     {% endfor %}
                    </ul>
                  </li>
		  </ul>
		 <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
		    <li><a href="{% url 'jobboard:employer_add' %}">Add Employer</a></li>
		    <li><a href="{% url 'jobboard:job_add' %}">Add Job</a></li>
                    
                    <li><a href="{% url 'auth_logout' %}"> Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-user"></span> Log In</a></li>
                    {% endif %}
		    <li><a href="{% url 'timeclock:index' %}">Timeclock</a></li>
		    {% if user.is_superuser %}
			<li><a href="{% url 'admin:app_list' 'jobboard' %}">Admin</a></li>
		    {% endif %}
		    <li><a href="http://mysite.smg247.webfactional.com">Other Apps</a></li>
                </ul>

	    </div>
	  </div>
	</div> 
	<div class="content">
		{% if messages %}
		<div class="messages">
			{% for message in messages %}
				<p class={{message.tags}}>{{message}}</p>
			{% endfor %}
		</div>
		{% endif %}
		{% block content %}

		{% endblock %}
		
		<div class="footer">
		Created by: Stephen Goeddel<br />
		On: 10/9/2013
	</div>
	</div>

</body>

</html>

jobs/templates/basic_base.html
{% load staticfiles %}
<!DOCTYPE html> 
<html lang="en"> 
<head> 
        <meta charset="utf-8"> 
        {% block title %}<title>Job Board-Time Clockr</title>{% endblock %}
        <link rel ="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
        <link rel ="stylesheet" href="{% static 'style.css' %}">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script>
        <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
        {% block scripts %}{% endblock %}
</head>
<body>
        <div class="navbar navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
                <ul class="nav">
                  <li class="active">
                    <a class="brand" href="{% url 'jobboard:index' %}">Job Board-Time Clock</a>
                  </li>
                 <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'auth_logout' %}"> Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-user"></span> Log In</a></li>
                    {% endif %}
                    <li><a href="{% url 'jobboard:index' %}">Job Board</a></li>
                    <li><a href="{% url 'timeclock:index' %}">Time Clock</a></li>
		    <li><a href="http://mysite.smg247.webfactional.com">Other Apps</a></li>
                </ul>

            </div>
          </div>
        </div> 
        <div class="content">
	<div class="jumbotron">
        {% block content %}

        {% endblock %}
	</div>
                <div class="footer">
                Created by: Stephen Goeddel<br />
                On: 10/19/2013
        </div>
        </div>

</body>

</html>

jobs/templates/timeclock_base.html
{% load staticfiles %}
<!DOCTYPE html> 
<html lang="en"> 
<head> 
	<meta charset="utf-8"> 
	{% block title %}<title>Time Clock</title>{% endblock %}
	<link href='http://fonts.googleapis.com/css?family=Titillium+Web:600' rel='stylesheet' type='text/css'>
	<link rel ="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
	<link rel ="stylesheet" href="{% static 'style.css' %}">
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js" ></script>
	<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
	{% block scripts %}{% endblock %}
</head>
<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container">
		<ul class="nav">
		  <li class="active">
		    <a class="brand" href="{% url 'timeclock:index' %}">Time Clock</a>
		  </li>
		  </ul>
		 <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'auth_logout' %}"> Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'auth_login' %}"><span class="glyphicon glyphicon-user"></span> Log In</a></li>
                    {% endif %}
		    <li><a href="{% url 'jobboard:index' %}">Job Board</a></li>	
		    {% if user.is_superuser %}
			<li><a href="{% url 'admin:app_list' 'timeclock' %}">Admin</a></li>
		    {% endif %}
		    <li><a href="http://mysite.smg247.webfactional.com">Other Apps</a></li>
		</ul>
	    </div>
	  </div>
	</div> 
	<div class="content">
		{% if messages %}
		<div class="messages">
			{% for message in messages %}
				<p class={{message.tags}}>{{message}}</p>
			{% endfor %}
		</div>
		{% endif %}
		{% block content %}

		{% endblock %}
		
		<div class="footer">
			Created by: Stephen Goeddel<br />
			On: 10/19/2013
		</div>
	</div>

</body>

</html>